language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl-bin TARGET=qlot
    - LISP=sbcl-bin TARGET=bundle

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/master/scripts/install-for-ci.sh | sh
  - bundle install

before_script:
  - ros --version
  - ros config

script:
  - make -f travis/Makefile $TARGET
