language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl-bin TARGET=qlot
    - LISP=sbcl-bin TARGET=bundle

install:
  - case "$TARGET" in 
      qlot)
        curl -L https://raw.githubusercontent.com/snmsts/roswell/master/scripts/install-for-ci.sh | sh
        ;;
      bundle)
        sudo apt-get install sbcl
        ;;
    esac
  - bundle install

script:
  - ./configure
  - make $TARGET-build
  - make cucumber
