language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl-bin

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/master/scripts/install-for-ci.sh | sh

before_script:
  - ros --version
  - ros config

script:
  - ros -l .sbcl-disable-debugger.lisp -s uiop -e '(/ 1 0)'
