language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl-bin

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/master/scripts/install-for-ci.sh | sh

before_script:
  - ros --version
  - ros config

script:
  - set -e
  - ros -l .sbcl-disable-debugger.lisp  -s qlot  -e '(qlot:install)'   -e '(push :standalone *features*)' -e '(qlot:quickload :gdid)'  -e '(gdid::dump)'
  - ./gdid --version
